/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.candy.demo;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.showLog());
        System.out.println("Value: " + classUnderTest.getSome(2, 3));
    }
}
