/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.candy.demo;

public class Library {

  public boolean showLog() {
    System.out.println("HELLO WORLD");
    return true;
  }

  public int getSome(int v1, int v2) {
    return v1 + v2;
  }
}
